name: Build Private IDE
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # 或 windows-latest / ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Clone private repo
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_TOKEN }}@github.com/voideditor-dev/ide.git
          cd ide
          ls -la

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.3
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev
          # 增加网络超时以处理慢速连接
          npm config set fetch-timeout 300000
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm install
          npm install -g node-gyp
          npm install -g gulp-cli

      - name: Build
        run: cd ide && npm run buildreact && npm run gulp vscode-linux-x64-min
